[metadata]
license = MIT
license_file = LICENSE
url = https://github.com/tamimystic/chokkhu

project_urls =
    Bug Tracker = https://github.com/tamimystic/chokkhu/issues
    Source Code = https://github.com/tamimystic/chokkhu

classifiers =
    Development Status :: 2 - Pre-Alpha
    Intended Audience :: Developers
    Intended Audience :: Science/Research
    License :: OSI Approved :: MIT License
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Operating System :: OS Independent
    Topic :: Scientific/Engineering :: Artificial Intelligence


[options]
package_dir =
    = src
packages = find:
python_requires = >=3.8
install_requires =
    numpy
    Pillow
    matplotlib
    seaborn
    pandas
    opencv-python-headless
    tqdm
    scipy


[options.packages.find]
where = src


[options.extras_require]
testing =
    pytest>=7.2,<9.0
    flake8>=6.1,<8.0
    mypy>=1.5,<2.0

dev =
    black>=23.3,<25.0
    isort>=5.12,<7.0
    build>=1.0,<2.0
    twine>=4.0,<6.0
    pytest>=7.2
    flake8>=6.1
    mypy>=1.5


[options.package_data]
chokkhu = py.typed


[flake8]
max-line-length = 160
extend-ignore = E203, W503
exclude =
    __init__.py
    build
    dist


[mypy]
mypy_path = src
ignore_missing_imports = True
follow_imports = skip
strict_optional = False
disallow_untyped_defs = False
check_untyped_defs = False
warn_return_any = False
warn_unused_ignores = False


